name: Deploy public folder to Firebase Hosting

on:
  push:
    branches:
      - main  # Change if your deployment branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy public folder to Firebase Hosting
      run: npx firebase deploy --only hosting --token "$FIREBASE_TOKEN"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
